from settings import *

indoor_tuple_list = [{'x': 375, 'y': 4, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},
              {'x': 395, 'y': 4, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},
              {'x': 415, 'y': 4, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},
              {'x': 435, 'y': 4, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},
              {'x': 453, 'y': 2, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': -28},
              {'x': 470, 'y': 2, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 32, 'offset_y': 24},
              {'x': 488, 'y': 2, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 505, 'y': 2, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 453, 'y': 20, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 470, 'y': 20, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 487, 'y': 20, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 505, 'y': 20, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 392, 'y': 44, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 376, 'y': 60, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 392, 'y': 60, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 376, 'y': 76, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 392, 'y': 76, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 415, 'y': 41, 'width': 64, 'height': 52, 'scale_width': 4 * TILE_WIDTH, 'scale_height': 3.25 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': 0.15625 * TILE_HEIGHT},
              {'x': 486, 'y': 39, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 505, 'y': 39, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 488, 'y': 53, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 506, 'y': 54, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 377, 'y': 99, 'width': 32, 'height': 36, 'scale_width': 2 * TILE_WIDTH, 'scale_height': 2.25 * TILE_HEIGHT},
              {'x': 415, 'y': 99, 'width': 16, 'height': 19, 'scale_width': TILE_WIDTH, 'scale_height': 1.1875 * TILE_HEIGHT},
              {'x': 437, 'y': 98, 'width': 47, 'height': 20, 'scale_width': 2.9375 * TILE_WIDTH, 'scale_height': 1.25 * TILE_HEIGHT},
              {'x': 486, 'y': 99, 'width': 32, 'height': 18, 'scale_width': 2 * TILE_WIDTH, 'scale_height': 1.125 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': -0.4375 * TILE_HEIGHT},
              {'x': 525, 'y': 71, 'width': 26, 'height': 12, 'scale_width': 1.625 * TILE_WIDTH, 'scale_height': 0.75 * TILE_HEIGHT, 'offset_x': 12, 'offset_y': -44},
              {'x': 553, 'y': 73, 'width': 26, 'height': 38, 'scale_width': 1.625 * TILE_WIDTH, 'scale_height': 2.375 * TILE_HEIGHT, 'offset_x': -20, 'offset_y': 0},
              {'x': 586, 'y': 71, 'width': 32, 'height': 40, 'scale_width': 2 * TILE_WIDTH, 'scale_height': 2.5 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': 32},
              {'x': 620, 'y': 89, 'width': 12, 'height': 21, 'scale_width': 0.75 * TILE_WIDTH, 'scale_height': 1.3125 * TILE_HEIGHT, 'offset_x': 8, 'offset_y': 28},
              {'x': 639, 'y': 74, 'width': 31, 'height': 37, 'scale_width': 1.9375 * TILE_WIDTH, 'scale_height': 2.3125 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': 0},
              {'x': 527, 'y': 271, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 511, 'y': 287, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 527, 'y': 287, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 511, 'y': 303, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 527, 'y': 303, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 415, 'y': 122, 'width': 31, 'height': 29, 'scale_width': 1.9375 * TILE_WIDTH, 'scale_height': 1.8125 * TILE_HEIGHT, 'offset_x': 4, 'offset_y': -20},
              {'x': 415, 'y': 153, 'width': 31, 'height': 29, 'scale_width': 1.9375 * TILE_WIDTH, 'scale_height': 1.8125 * TILE_HEIGHT, 'offset_x': 4, 'offset_y': -20},
              {'x': 415, 'y': 185, 'width': 31, 'height': 33, 'scale_width': 1.9375 * TILE_WIDTH, 'scale_height': 2.0625 * TILE_HEIGHT, 'offset_x': 4, 'offset_y': -20},
              {'x': 393, 'y': 143, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 377, 'y': 159, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 393, 'y': 159, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 377, 'y': 175, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 393, 'y': 175, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 377, 'y': 191, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 393, 'y': 191, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 377, 'y': 207, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 393, 'y': 207, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 377, 'y': 207, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': 0, 'flip_x': False, 'flip_y': True},
              {'x': 393, 'y': 207, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': 0, 'flip_x': False, 'flip_y': True},
              {'x': 380, 'y': 228, 'width': 26, 'height': 16, 'scale_width': 1.625 * TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': -20, 'offset_y': 20},
              {'x': 450, 'y': 122, 'width': 32, 'height': 40, 'scale_width': 2 * TILE_WIDTH, 'scale_height': 2.5 * TILE_HEIGHT},
              {'x': 489, 'y': 125, 'width': 16, 'height': 26, 'scale_width': TILE_WIDTH, 'scale_height': 1.625 * TILE_HEIGHT},
              {'x': 507, 'y': 129, 'width': 32, 'height': 22, 'scale_width': 2 * TILE_WIDTH, 'scale_height': 1.625 * TILE_HEIGHT},
              {'x': 544, 'y': 119, 'width': 32, 'height': 32, 'scale_width': 2 * TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT, 'offset_x': 4, 'offset_y': 4},
              {'x': 584, 'y': 121, 'width': 32, 'height': 32, 'scale_width': 2 * TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},
              {'x': 620, 'y': 121, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': -12},
              {'x': 638, 'y': 121, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': -16},
              {'x': 451, 'y': 167, 'width': 32, 'height': 16, 'scale_width': 2 * TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': 24},
              {'x': 452, 'y': 188, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': 24},
              {'x': 490, 'y': 171, 'width': 17, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': -12},
              {'x': 490, 'y': 213, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': 36},
              {'x': 512, 'y': 159, 'width': 64, 'height': 38, 'scale_width': 4 * TILE_WIDTH, 'scale_height': 2.375 * TILE_HEIGHT},
              {'x': 585, 'y': 158, 'width': 32, 'height': 40, 'scale_width': 2 * TILE_WIDTH, 'scale_height': 2.5 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': 32},
              {'x': 638, 'y': 163, 'width': 32, 'height': 34, 'scale_width': 2 * TILE_WIDTH, 'scale_height': 2.125 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': -8},
              {'x': 372, 'y': 249, 'width': 16, 'height': 48, 'scale_width': TILE_WIDTH, 'scale_height': 3 * TILE_HEIGHT},
              {'x': 389, 'y': 249, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},
              {'x': 406, 'y': 249, 'width': 16, 'height': 48, 'scale_width': TILE_WIDTH, 'scale_height': 3 * TILE_HEIGHT},
              {'x': 427, 'y': 237, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 427, 'y': 254, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 427, 'y': 283, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 444, 'y': 283, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 461, 'y': 283, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 444, 'y': 278, 'width': 16, 'height': 4, 'scale_width': TILE_WIDTH, 'scale_height': 0.25 * TILE_HEIGHT},
              {'x': 481, 'y': 283, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 481, 'y': 278, 'width': 16, 'height': 4, 'scale_width': TILE_WIDTH, 'scale_height': 0.25 * TILE_HEIGHT},
              {'x': 481, 'y': 255, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': 8},
              {'x': 427, 'y': 271, 'width': 16, 'height': 4, 'scale_width': TILE_WIDTH, 'scale_height': 0.25 * TILE_HEIGHT},
              {'x': 547, 'y': 273, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},
              {'x': 566, 'y': 273, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},
              {'x': 586, 'y': 273, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},
              {'x': 605, 'y': 273, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},

              {'x': 527, 'y': 204, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 543, 'y': 204, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 559, 'y': 204, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},

              {'x': 511, 'y': 220, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 527, 'y': 220, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 543, 'y': 220, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 559, 'y': 220, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 575, 'y': 220, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},

              {'x': 511, 'y': 236, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 527, 'y': 236, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 543, 'y': 236, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 559, 'y': 236, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 575, 'y': 236, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},

              {'x': 527, 'y': 252, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 543, 'y': 252, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 559, 'y': 252, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},

              {'x': 594, 'y': 236, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 610, 'y': 236, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 594, 'y': 252, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 610, 'y': 252, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},

              {'x': 627, 'y': 272, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 643, 'y': 272, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 627, 'y': 288, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 643, 'y': 288, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 627, 'y': 304, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
              {'x': 643, 'y': 304, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},

              {'x': 630, 'y': 239, 'width': 16, 'height': 26, 'scale_width': TILE_WIDTH, 'scale_height': 1.625 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': 16},
              {'x': 649, 'y': 220, 'width': 32, 'height': 48, 'scale_width': 2 * TILE_WIDTH, 'scale_height': 3 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': -4},

              {'x': 526, 'y': 1, 'width': 160, 'height': 64, 'scale_width': 10 * TILE_WIDTH, 'scale_height': 4 * TILE_HEIGHT},

              {'x': 461, 'y': 271, 'width': 16, 'height': 4, 'scale_width': TILE_WIDTH, 'scale_height': 0.25 * TILE_HEIGHT},

              {'x': 461, 'y': 254, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},

              {'x': 461, 'y': 237, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},

              {'x': 377, 'y': 207, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': 0, 'flip_x': True, 'flip_y': True},]
