from settings import *

poke_market_tuple_list = [{'x': 432, 'y': 16, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 448, 'y': 32, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 464, 'y': 32, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 464, 'y': 48, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 448, 'y': 48, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 432, 'y': 80, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 448, 'y': 96, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 576, 'y': 16, 'width': 16, 'height': 48, 'scale_width': TILE_WIDTH, 'scale_height': 3 * TILE_HEIGHT},
                          {'x': 592, 'y': 16, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},
                          {'x': 608, 'y': 16, 'width': 16, 'height': 48, 'scale_width': TILE_WIDTH, 'scale_height': 3 * TILE_HEIGHT},
                          {'x': 576, 'y': 80, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 592, 'y': 80, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 608, 'y': 80, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 576, 'y': 96, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 608, 'y': 96, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 576, 'y': 112, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 592, 'y': 112, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 608, 'y': 112, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 624, 'y': 80, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 640, 'y': 80, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 624, 'y': 96, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 640, 'y': 96, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 433, 'y': 160, 'width': 34, 'height': 32, 'scale_width': 2.125 * TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT, 'offset_x': 4, 'offset_y': 0},
                          {'x': 480, 'y': 160, 'width': 34, 'height': 37, 'scale_width': 2.125 * TILE_WIDTH, 'scale_height': 2.3125 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': 20},
                          {'x': 528, 'y': 160, 'width': 32, 'height': 32, 'scale_width': 2 * TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},
                          {'x': 560, 'y': 160, 'width': 32, 'height': 32, 'scale_width': 2 * TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},
                          {'x': 433, 'y': 216, 'width': 22, 'height': 24, 'scale_width': 1.375 * TILE_WIDTH, 'scale_height': 1.5 * TILE_HEIGHT, 'offset_x': 4, 'offset_y': 0},
                          {'x': 457, 'y': 216, 'width': 22, 'height': 24, 'scale_width': 1.375 * TILE_WIDTH, 'scale_height': 1.5 * TILE_HEIGHT, 'offset_x': -28, 'offset_y': 0},
                          {'x': 481, 'y': 216, 'width': 22, 'height': 24, 'scale_width': 1.375 * TILE_WIDTH, 'scale_height': 1.5 * TILE_HEIGHT, 'offset_x': 4, 'offset_y': 0},
                          {'x': 505, 'y': 216, 'width': 22, 'height': 24, 'scale_width': 1.375 * TILE_WIDTH, 'scale_height': 1.5 * TILE_HEIGHT, 'offset_x': -28, 'offset_y': 0},
                          {'x': 544, 'y': 208, 'width': 51, 'height': 36, 'scale_width': 3.1875 * TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': 16},
                          {'x': 608, 'y': 304, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': 16, 'flip_x': True, 'flip_y': False},
                          {'x': 640, 'y': 234, 'width': 20, 'height': 16, 'scale_width': 1.25 * TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': 16},
                          {'x': 640, 'y': 218, 'width': 20, 'height': 10, 'scale_width': 1.25 * TILE_WIDTH, 'scale_height': 0.625 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': 16},
                          {'x': 490, 'y': 278, 'width': 28, 'height': 13, 'scale_width': 1.75 * TILE_WIDTH, 'scale_height': 0.8125 * TILE_HEIGHT, 'offset_x': -24, 'offset_y': 12},
                          {'x': 608, 'y': 144, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 624, 'y': 144, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 624, 'y': 160, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 624, 'y': 176, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 608, 'y': 165, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': 20},
                          {'x': 640, 'y': 160, 'width': 16, 'height': 32, 'scale_width': TILE_WIDTH, 'scale_height': 2 * TILE_HEIGHT},

                          {'x': 624, 'y': 32, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': 0, 'flip_x': False, 'flip_y': True},
                          {'x': 624, 'y': 32, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': 0, 'flip_x': True, 'flip_y': True},
                          {'x': 624, 'y': 32, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},
                          {'x': 624, 'y': 32, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT, 'offset_x': 0, 'offset_y': 0, 'flip_x': True, 'flip_y': False},

                          {'x': 592, 'y': 48, 'width': 16, 'height': 16, 'scale_width': TILE_WIDTH, 'scale_height': TILE_HEIGHT},

                          {'x': 480, 'y': 160, 'width': 16, 'height': 37, 'scale_width': TILE_WIDTH, 'scale_height': 2.3125 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': 20},
                          {'x': 496, 'y': 160, 'width': 16, 'height': 37, 'scale_width': TILE_WIDTH, 'scale_height': 2.3125 * TILE_HEIGHT, 'offset_x': 0, 'offset_y': 20},]
